import logging
from src.core.router import IntentRouter

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class BrainOrchestrator:
    """
    The central coordinator of the GuildLM system.
    Receives user requests, delegates to the IntentRouter, and orchestrates execution across Guilds.
    """
    
    def __init__(self):
        self.router = IntentRouter()
        
    def execute_request(self, user_prompt: str) -> str:
        """
        Executes an end-to-end user request.
        """
        logger.info(f"Received Request: '{user_prompt}'")
        
        # 1. Classify Intent
        classification = self.router.classify_intent(user_prompt)
        
        # 2. Select Specialist
        specialist_id = self.router.select_specialist(classification)
        logger.info(f"Routing to Specialist: {specialist_id}")
        
        # 3. Load & Run Specialist (Simulation)
        response = self._run_specialist(specialist_id, user_prompt)
        
        # 4. Optional: Cross-Guild Review (e.g., Code -> Legal Compliance)
        # Not implemented in Phase 1
        
        return response
        
    def _run_specialist(self, specialist_id: str, prompt: str) -> str:
        """
        Simulates dynamically loading a LoRA adapter for a specific guild and executing inference.
        In production, this talks to an inference server (vLLM / Ollama) via an API.
        """
        logger.info(f"Loading SLM Adapter: {specialist_id}...")
        
        if specialist_id == "guild-code/go_generator":
            return "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"Generated by Go Generator SLM\")\n}"
        elif specialist_id == "guild-code/go_reviewer":
            return "Review complete. The Go code looks structurally sound but lacks error handling."
        else:
            return "I am the generalist Brain model. I couldn't find a specialized guild for this request."

# Example Usage
if __name__ == "__main__":
    brain = BrainOrchestrator()
    
    # Test Code Guild routing
    res1 = brain.execute_request("Can you build a high performance HTTP API in Go?")
    print(f"Response: {res1}\n")
    
    # Test Review routing
    res2 = brain.execute_request("Please review this Go file for race conditions.")
    print(f"Response: {res2}\n")
    
    # Test unknown routing
    res3 = brain.execute_request("Write me a poem about the sea.")
    print(f"Response: {res3}\n")
